name: Daily Commit

on:
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * *'

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to push changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add daily commit - 23f3000916@ds.study.iitm.ac.in
        run: |
          echo "Daily update: $(date)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily commit: $(date)" || echo "Nothing to commit"
          git push
