name: Daily Commit

on:
  workflow_dispatch:         # ✅ Allows manual trigger from the GitHub UI
  schedule:
    - cron: '30 5 * * *'     # ✅ Runs daily at 05:30 UTC (adjust as needed)

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add daily commit - 23f3000916@ds.study.iitm.ac.in
        run: |
          echo "Daily update: $(date)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily commit: $(date)"
          git push
